"""Turns assets/spaceman.gif into src/spaceman_data.h for the firmware.

The seller's spaceman is an 80x80, 20-frame animation, white on black.
Stored as a GIF it would need a decoder and ~22KB of the clock's memory,
so instead every frame is converted here, on the PC, into 16 shades of
grey and run-length encoded: each byte is (shade << 4) | (run length - 1),
runs of 1-16 pixels, left to right, top to bottom. That is ~26KB of
firmware and needs almost no memory to draw.

Run from the repo root:  python3 tools/make_spaceman.py
Needs Pillow:            pip install pillow
"""
from pathlib import Path

from PIL import Image

SOURCE = Path("assets/spaceman.gif")
OUTPUT = Path("src/spaceman_data.h")
SHADES = 16


def encode(pixels):
    shades = [round(p * (SHADES - 1) / 255) for p in pixels]
    out, i = [], 0
    while i < len(shades):
        j = i
        while j < len(shades) and shades[j] == shades[i] and j - i < 16:
            j += 1
        out.append((shades[i] << 4) | (j - i - 1))
        i = j
    return out


def main():
    gif = Image.open(SOURCE)
    width, height = gif.size
    data, offsets, durations = [], [], []
    for n in range(gif.n_frames):
        gif.seek(n)
        durations.append(gif.info.get("duration", 100))
        offsets.append(len(data))
        data += encode(gif.convert("L").tobytes())
    assert len(data) < 65536, "offsets are 16-bit"
    frame_ms = max(10, round(sum(durations) / len(durations)))

    lines = [
        "// Generated by tools/make_spaceman.py from assets/spaceman.gif - do not edit.",
        "#pragma once",
        "",
        f"constexpr int16_t SPACEMAN_W = {width};",
        f"constexpr int16_t SPACEMAN_H = {height};",
        f"constexpr uint8_t SPACEMAN_FRAMES = {len(offsets)};",
        f"constexpr uint16_t SPACEMAN_FRAME_MS = {frame_ms};  // from the GIF",
        "",
        "static const uint16_t SPACEMAN_OFFSETS[] PROGMEM = {",
        "  " + ", ".join(map(str, offsets)) + ",",
        "};",
        "",
        f"// {len(data)} bytes",
        "static const uint8_t SPACEMAN_RLE[] PROGMEM = {",
    ]
    for i in range(0, len(data), 20):
        lines.append("  " + ", ".join(f"0x{b:02X}" for b in data[i:i + 20]) + ",")
    lines += ["};", ""]
    OUTPUT.write_text("\n".join(lines))
    print(f"{OUTPUT}: {gif.n_frames} frames, {width}x{height}, {len(data)} bytes, {frame_ms} ms/frame")


if __name__ == "__main__":
    main()
